---
- name: Debian | Install Standard Packages for a Server
  ansible.builtin.apt:
    name: "{{UbuntuServer}}"
    update-cache: yes
    cache_valid_time: 300    
    state: present
  when: SystemType|default('Server') == "Server"


- name: Debian | Install Standard Packages for a Desktop
  ansible.builtin.apt:
    name: "{{UbuntuDesktop}}"
    update-cache: yes
    cache_valid_time: 300
    state: present
  when: SystemType|default('Server') == "Desktop"