---


- name: RedHat| Install epel repository
  ansible.builtin.apt:
    name: epel-release
    state: present
  register: epel_installed
  delay: 10
  retries: 12
  until: epel_installed is successful 

- name: RedHat| Reboot after installing epel repo
  ansible.builtin.shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: epel_installed is changed

- name: RedHat| Wait for the reboot to complete
  ansible.builtin.wait_for_connection:
    connect_timeout: 30
    sleep: 5
    delay: 20
    timeout: 300
  when: epel_installed is changed

- name: RedHat| Install RedHat Packages
  ansible.builtin.apt:
    name: "{{RedHat}}"
    state: present
  when: SystemType|default('Server') == "Server"
